version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - git config --global user.email "eng.omar.higgy@gmail.com"
      - git config --global user.name "eng.omar.higgy"
      - git clone https://github.com/eng-omarhiggy/create-nodejs-project.git
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - git checkout main
      - git add .
      - git commit -m "new"
      - git push origin main
